### ISSUE TITLE
null key

### ISSUE THREAD

**Issue by jglapa** [vlsi/compactmap#4]
Hi, is there anything preventing from support of  `null` keys?
I understand that underneath dexx collection is used.
 But is that the limitation or compactmap itself?

```
Exception in thread "main" java.lang.NullPointerException
	at com.github.andrewoma.dexx.collection.internal.hashmap.CompactHashMap.elemHashCode(CompactHashMap.java:78)
	at com.github.andrewoma.dexx.collection.internal.hashmap.CompactHashMap.computeHash(CompactHashMap.java:89)
	at com.github.andrewoma.dexx.collection.internal.hashmap.CompactHashMap.get(CompactHashMap.java:65)
	at com.github.andrewoma.dexx.collection.HashMap.get(HashMap.java:102)
	at vlsi.utils.CompactHashMapClass.put(CompactHashMapClass.java:76)
	at vlsi.utils.CompactHashMap.put(CompactHashMap.java:105)
```

PS. we see huge memory savings with help of this library

**Comment by jglapa** [comment]
hey @vlsi just wanted to realistically ask if there is any chance to get that `null` key wrapping any time soon?

**Comment by vlsi** [comment]
Well, it seems simple, however the sad thing is CompactMap does not have unit tests for the map.
In other words, adding null support probably requires verification that it is supported for all the APIs like `entrySet().iterator().next().setKey(null)`.

It is not clear if something like https://github.com/google/guava/blob/v25.0/android/guava-testlib/src/com/google/common/collect/testing/MapTestSuiteBuilder.java could automate tests

**Comment by vlsi** [comment]
@jglapa , could you please check if current `master` works for you?

**Comment by vlsi** [comment]
Fixed in 1.3.0

**Comment by jglapa** [comment]
oh wow, I just noticed you implemented this. 
And I  just submitted a PR with that Guava test suite to help you with this.
Please close that https://github.com/vlsi/compactmap/pull/5 and I'll start testing:)

Thanks a lot!

**Comment by jglapa** [comment]
@vlsi first impression shows it works great! Thanks a lot for the quick fix.
